-- MySQL Script generated by MySQL Workbench
-- Thu Oct 18 15:48:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ReviewCollector
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ReviewCollector
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ReviewCollector` DEFAULT CHARACTER SET utf8 ;
USE `ReviewCollector` ;

-- -----------------------------------------------------
-- Table `ReviewCollector`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReviewCollector`.`User` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(300) NOT NULL,
  `dateCreated` TIMESTAMP NULL DEFAULT 'CURRENT_TIMESTAMP',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ReviewCollector`.`Application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReviewCollector`.`Application` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `operatingSystem` ENUM('Android', 'iOS') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ReviewCollector`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReviewCollector`.`Review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `appId` INT NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  `temporalContext` ENUM('Intensive', 'Allocative') NOT NULL,
  `spatialContext` ENUM('Visiting', 'Traveling', 'Wandering') NOT NULL,
  `socialContext` ENUM('Constraining', 'Encouraging') NOT NULL,
  `textReview` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `userId_FK_idx` (`userId` ASC) VISIBLE,
  INDEX `appId_FK_idx` (`appId` ASC) VISIBLE,
  CONSTRAINT `userId_FK`
    FOREIGN KEY (`userId`)
    REFERENCES `ReviewCollector`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `appId_FK`
    FOREIGN KEY (`appId`)
    REFERENCES `ReviewCollector`.`Application` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ReviewCollector`.`Images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReviewCollector`.`Images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reviewId` INT NOT NULL,
  `filename` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `filename_UNIQUE` (`filename` ASC) VISIBLE,
  INDEX `reviewId_FK_idx` (`reviewId` ASC) VISIBLE,
  CONSTRAINT `reviewId_FK`
    FOREIGN KEY (`reviewId`)
    REFERENCES `ReviewCollector`.`Review` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
